-- =============================================================================
-- Juwa2 Customer Support — Supabase SQL setup (READ THIS FIRST)
-- =============================================================================
--
-- Run IN ORDER in Supabase → SQL Editor (one file at a time):
--
--   SCENARIO A — Brand-new empty Supabase project
--     1) Skip 1_reset.sql
--     2) Run  2_bootstrap.sql
--     3) Run  3_extras.sql
--     4) Run  5_game_sso.sql   (in-app game chat SSO)
--     5) Run  6_channel_labels.sql  (Website / Juwa App inbox labels)
--     6) Run  6b_backfill_channel_labels.sql  (tag existing threads — optional)
--     7) Run  6_auto_approve_customers.sql  (instant customer signup approval)
--     8) Run  7_unread_inbox_label.sql  (auto Unread label on unread customer messages)
--     9) Run  8_staff_inbox_scope.sql  (assign support staff to Website / App / Both inboxes)
--    10) Run  9a_technical_role_enum.sql  (ALONE — adds technical role enum value)
--    11) Run  9_technical_escalations.sql  (support → technical handoff queue)
--    12) Run  9b_technical_escalation_label_access.sql  (technical inbox sees labeled threads)
--
--   SCENARIO B — Bootstrap already ran; "already exists" / policy errors
--     Run 3_extras.sql, 5_game_sso.sql, and 6_auto_approve_customers.sql as needed  (safe to re-run)
--
--   SCENARIO C — Wipe app data and start over (keeps auth.users)
--     1) Run  1_reset.sql
--     2) Run  2_bootstrap.sql
--     3) Run  3_extras.sql
--
-- Do NOT run schema.sql — use the numbered files above.
--
-- ADMIN LOGIN (password lives in Supabase Auth, not in your project folder):
--   1) Dashboard → Authentication → Users → Add user
--        juwa2support@gmail.com + password + Auto Confirm User
--   2) SQL Editor → run 4_create_admin.sql
--   3) Sign in at your app /login → opens /dashboard
-- =============================================================================
